### PR TITLE
PSR-17 support

### PR DESCRIPTION
**Pull request by boesing**
|    Q          |   A
|-------------- | ------
| BC Break      | no
| New Feature   | yes

### Description

As already done in mezzio/mezzio#75, mezzio/mezzio-router#23, mezzio/mezzio-problem-details#19 and mezzio/mezzio-hal#43 this PR provides support for PSR-17 response factory.

### CODE REVIEW

**Comment by Ocramius** [comment]
Moved to `1.3.0`, since `1.2.0` is just about PHP 8.1 support

**Comment by Ocramius** [comment]
Oof, this is on me, removing milestone, releasing and re-adding: didn't have time to look at this yet, sorry :(

**Comment by weierophinney** [comment]
@boesing I rebased for you. :smile:

**Review by weierophinney — APPROVED** [review]
:ship:

**Pull request merged**
